### ISSUE TITLE
Request to api.hellbz.de has changed

### ISSUE THREAD

**Issue by HellBz** [GravityWolfNotAmused/PlayerCountDiscordBot#61]
Hello Admin,

please set the User-Agent to my API-Request like the following 

https://api.hellbz.de//scum/api.php?address=176.57.181.82&port=28700

With a New Formated and validated User-Agent in this Format

Bot-Name/Version (Author-Name; Author-Website; Author-Contact Website or E-Mail; Additional Informations)

For example:
SCUM-List-Crawler/1.0 (HellBz; https://hellbz.de; cofing@hellbz.de; Some more you like to tell me..)

Best Regards,

Stefan

**Comment by GravityWolfNotAmused** [comment]
I appreciate you reaching out to me in regards to your API change. I marked your service as obsolete and removed support for it as it was not as performant as BattleMetrics, and users said that it was too slow when providing up-to-date information about their player counts.

I am more interested in capturing this information for my users over utilizing another service; however, it seems to be less of a priority due to BattleMetrics filling in most gaps. Is there an argument to be made for using your service?

**Comment by GravityWolfNotAmused** [comment]
https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/blob/0aac4b6fb8475d66d9719e64758e7a04ac527daf/DiscordPlayerCountBot/Providers/ScumProvider.cs#L3

**Comment by HellBz** [comment]
Or you capture Datas directly from Master-Server-List

I Write a Protocoll for GameQ from AustinB

https://gist.github.com/HellBz/bebf71ff2d873c7261c94a6e8ea1c55b
